### PR TITLE
Allow HTTPlug 2 (and hence PSR-18)

### PR DESCRIPTION
**Pull request by Jean85**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Documentation   | not yet
| License         | MIT

#### What's in this PR?
This PR allows HTTPlug 2, and hence PSR-18. This is WIP to start a build and see if there is some compat issue to be resolved.

#### Checklist

- [x] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

#### To Do
- [x] Check the build
- [ ] Check if any doc PR is needed
- [x] Check if any compat fix is needed

### CODE REVIEW

**Comment by dbu** [comment]
we do not need a new release of discovery, right?

**Comment by Jean85** [comment]
Since this is a change in the `composer.json` to allow HTTPlug 2, yes @dbu, we need a new (minor?) release. That's the main reason that pushed me toward this PR :smile:

**Comment by dbu** [comment]
the change is only in require-dev though, so its only relevant for the build of this repository, not for any consumers of discovery.

**Comment by Jean85** [comment]
Oh you're right, I didn't change anything outside of the test build! Good! :+1:

**Pull request merged**
