### PR TITLE
Renamed class Puli to PuliBetaStrategy

### PR DESCRIPTION
**Pull request by Nyholm**
As requested in #62

### CODE REVIEW

**Comment by dbu** [comment]
you missed some phpspec files, hence the test failures.

apart from that, i think this makes sense.

**Comment by Nyholm** [comment]
Thank you. Sorry for that.

**Comment by sagikazarmark** [comment]
Squash then I merge it.

**Comment by sagikazarmark** [comment]
Cool, didn't know about this feature.

**Pull request merged**
