### PR TITLE
Prepare for new release

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by tuupola** [comment]
https://github.com/php-http/discovery/blob/2cbe708f5a09a4b672ba4fa04b31d414fc51a0fd/composer.json#L25

Maybe this should be update too to say _"Allow to use Guzzle, Diactoros or Slim Framework factories"_. Missed it myself.

**Comment by Nyholm** [comment]
Sure!

**Comment by Nyholm** [comment]
See #83

**Comment by tuupola** [comment]
Thanks!

**Pull request merged**
