### PR TITLE
Moved Symfony before Buzz

### PR DESCRIPTION
**Pull request by Nyholm**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| Documentation   | 
| License         | MIT

I moved Symfony before Buzz since it is fairly more used and maintained. Im not sure if this list should be ordered by popularity, performance, most likeable or random. But this *feels* better.

### CODE REVIEW

**Comment by Nyholm** [comment]
Should we update order on the HTTPlug adapters too? @dbu @sagikazarmark?

**Comment by sagikazarmark** [comment]
I'm okay if we suggest a better maintained client. It only matters anyway if there are multiple ones installed.

For the user it shouldn't really matter, they should rely on the interface. The only thing that would impact them is a client not adhering the standard or performance differences. Again, I think we can make the better choice for the user in those cases as well.

**Comment by Nyholm** [comment]
Okey. Thank you for the input. I've updated the PR

**Comment by Nyholm** [comment]
Thank you for the reviews

**Pull request merged**
