### PR TITLE
Add support for nyholm/psr7

### PR DESCRIPTION
**Pull request by pyrech**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | partially #103
| Documentation   | Todo
| License         | MIT

Add support for `nyholm/psr7`'s factories.

### CODE REVIEW

**Comment by pyrech** [comment]
Is this PR wanted? I'm using my fork for now but it would be awesome if this PR could be merged and deployed soon! 😉 
Thanks!

**Comment by pyrech** [comment]
It was mentionned in the related issue. Nyholm is the lightest and the more complete PSR implementation. IMO it has its place as the recommended implementation to use by default

**Comment by Nyholm** [comment]
Changing the order is fine according to our bc promise: http://php-http.readthedocs.io/en/latest/httplug/backwards-compatibility.html

**Comment by dbu** [comment]
@pyrech do you try this out in your project quickly, just so we are 100% sure its all fine? then @Nyholm or me can tag a new minor version.

**Comment by pyrech** [comment]
I'm already using my fork on production but will switch back to this package asap and ping here when done :wink:

**Comment by pyrech** [comment]
Just tested it and it works :+1:

**Comment by dbu** [comment]
thanks. i tagged 1.4.0 with this.

**Pull request merged**
